#!/bin/bash
# manual install
flatpakdir="$HOME/.var/app/com.discordapp.Discord"
if [ -d /opt/Discord ]; then
  /opt/Discord/Discord &
elif [ -e /usr/bin/discord ]; then
# package install
  /usr/bin/discord &
elif [ -d $flatpakdir ]; then
  cd $HOME/.var
  ln -sf {app/com.discordapp.Discord,$XDG_RUNTIME_DIR}/discord-ipc-0
  flatpak run com.discordapp.Discord &
else
  echo "ERROR: Discord is either not installed or you are using the snap"
  echo " version, please install the discord package, flatpak or tarball."
  exit 1
fi
# give slowcord time to start
sleep 15
/usr/local/bin/fetchcord $@

